### ISSUE TITLE
For Global Web

### ISSUE THREAD

**Issue by irabro1992** [CrymanChen/iQIYI-Downloader#1]
hello , can you please add support for iq.com ( for international users.) it worked on free video. but when i download vip video , i can only download 5 mins of the video. i have vip membership. thank you for your amazing script.

**Comment by CrymanChen** [comment]
Provide me the account informstion privately.

**Comment by irabro1992** [comment]
> Provide me the account informstion privately.

please drop your telegram or something.

**Comment by CrymanChen** [comment]
email at the profile page.

**Comment by irabro1992** [comment]
email has been sent to your email. if u didn't see it , please check spam folder

**Comment by CrymanChen** [comment]
The question you mentioned about you can only download the first several minutes is that **you didn't add the cookies to the program**.  
Based on the test just now, when I sent a request without the cookies, the server returned a warning saying that "User not logged in: try to end authentication failed" (未登录用户：试看结束鉴权失败)  
![20230729025223](https://github.com/CrymanChen/iQIYI-Downloader/assets/106590233/6e4661dc-2473-4580-81da-602f7c3ef07a)
So the solution is that you should copy the cURL of the dash link, and add the cookies into it, and then the problem will be solved.  
![20230729025139](https://github.com/CrymanChen/iQIYI-Downloader/assets/106590233/8cd38a39-e751-403c-84c0-320f396fca5f)

**Comment by irabro1992** [comment]
thank you for the quick response. but how to add cookie to the program ? i am just a beginner. any guide would be help for me.

**Comment by CrymanChen** [comment]
Solution:  

1. Copy the cURL of the dash link. Go to curlconverter.com to convert the cURL to Python.
2. Copy both the cookies and the headers into the Python script.
`cookies = {
    'QC005': 'value1',
    'QC006': 'value2',
    ...}  
headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'}`  
3. In the line 39 https://github.com/CrymanChen/iQIYI-Downloader/blob/c4194788674768152e57593549c2fc04b50297ad/iqiyi.py#L39 replace this line with the content below:  
`request = requests.get(url=link, headers=headers, cookies=cookies)`
4. Save the file, and restart the program. Problem solved.

**Comment by CrymanChen** [comment]
You may now change your password in order to protect your account security.  
Appreciate that you came up with this question. Good job!

**Comment by irabro1992** [comment]
Sure. Do i need to change header and cookies when i need to download another episodes or other drama ?

**Comment by irabro1992** [comment]
> 2\. Copy both the cookies and the headers into the Python script.

i don't understand this path.  should i copy to iqipy.py ( line 39 ) ? or
should i save with notepad? damn. i am so stupid -_- . answer me if you can.
because i am the begineer.

**Comment by CrymanChen** [comment]
> Sure. Do i need to change header and cookies when i need to download another episodes or other drama ?  
>
Yes, you should do so, since each episode needs different cookies. Also, why not try it yourself?  
> should i copy to iqipy.py ( line 39 ) ? or should i save with notepad?  
>
Just like what the headers look like, I have already demonstrated in the original script.

**Comment by CrymanChen** [comment]
Thread closed. I appreciate your question. However, maybe we should try more and google it before you finally turn to others.
