### ISSUE TITLE
I'm dead

### ISSUE THREAD

**Issue by Fullna-ui** [CrymanChen/iQIYI-Downloader#10]
![Screenshot](https://github.com/user-attachments/assets/274b6e0d-8f7d-4056-9128-7d8b1569f0f5)

**Comment by Fullna-ui** [comment]
The DASH link I extracted by switching the resolution isn't correct. I don't understand anymore.

**Comment by Fullna-ui** [comment]
我就想趁爱奇艺又是版权到期下架前把动漫保存下来，会员都交了。。

**Comment by Fullna-ui** [comment]
以前没想到过了这几年发现很多曾经的番剧都不能看了，英译又不如中文，字幕组又不确定当初看的哪一家，像羚邦的更是完全没影子，我都快为此整吐了

**Comment by Fullna-ui** [comment]
现在只有爱奇艺上的正版没换字幕版本，但下不下来也成不了救赎啊

**Comment by Fullna-ui** [comment]
现在只有爱奇艺上的正版没换过字幕版本，但下不下来也成不了救赎啊，求求路过的好心大佬向无助可怜的我伸出援手

**Comment by Fullna-ui** [comment]
我就想趁爱奇艺又是版权到期下架前把动漫保存下来，会员都交了。。

以前没想到过了这几年发现很多曾经的番剧都不能看了，英译又不如中文，字幕组又不确定当初看的哪一家，像羚邦的更是完全没影子，我都快整吐了

现在只有爱奇艺上的正版没换过字幕版本，但下不下来也成不了救赎啊，求求路过的好心大佬向无助可怜的我伸出援手

**Comment by Fullna-ui** [comment]
我就想趁爱奇艺又是版权到期下架前把动漫保存下来，会员都交了。。

以前没想到过了这几年发现很多曾经的番剧都不能看了，英译又不如中文，字幕组又不确定当初看的哪一家，像羚邦的更是完全没影子，我都快整吐了

现在只有爱奇艺上的动漫没换过字幕版本，但下不下来也成不了救赎啊，求求路过的好心大佬向无助可怜的我伸出援手

**Comment by Fullna-ui** [comment]
恋如雨止好几年前在优酷上看的，最近得知被央视封了我人当场就傻眼了

**Comment by Fullna-ui** [comment]
恋如雨止好几年前在优酷上看的，最近得知被央视封了我人当场就傻眼了，而当时看的哪个版本是再也不知道了

**Comment by CrymanChen** [comment]
Spamming emotional words won't get you any help. Use at your own risk.
