### ISSUE TITLE
No m3u8 data.

### ISSUE THREAD

**Issue by Priveete** [CrymanChen/iQIYI-Downloader#2]
![image](https://github.com/CrymanChen/iQIYI-Downloader/assets/91370754/930dc18a-bc2a-4a21-915a-9a52d191087c)

**Comment by CrymanChen** [comment]
This script is aimed at the highest quality of the video. So if you don't have premium or have set the quality to 720p or lower, it could lead to this problem.  
I advise that you go to this page, and try searching "m3u8" and then edit the script based on your finding.  
Usually, you have to change the number 0 in the Line 44:  
https://github.com/CrymanChen/iQIYI-Downloader/blob/9905324e85c61add1b31c3f8af30ee1b8d630e10/iqiyi.py#L44  
And if the problem still exists, please input the URL of the video you are looking for, not only a screenshot. :)

**Comment by wanbangshucheng1** [comment]
我也遇到了这个问题，幻乐森林的任意一集，画质已设为1080P。同时，针对客户端的4K内容，其json并未包含M3U8信息和KID
