### ISSUE TITLE
这个能解析客户端的帧绮映画和杜比视界的视频吗

### ISSUE THREAD

**Issue by zimq** [CrymanChen/iQIYI-Downloader#3]
目前只用于解析网页端播放的是吗

**Comment by zimq** [comment]
另外文章里没看懂通过kid获取pssh是怎么获取的，能用于客户端的kid吗

**Comment by CrymanChen** [comment]
不能。
本程序中的所有功能均需要通过Chrome浏览器实现

**Comment by CrymanChen** [comment]
Quote: 另外文章里没看懂通过kid获取pssh是怎么获取的，能用于客户端的kid吗
请自行搜索Key ID和Protection System Specific Header
